//
// Created by twak on 14/10/2019.
//

#include "responsive_window.h"
#include "responsive_layout.h"
#include "screenshot.h"
#include <iostream>
#include <QApplication>
#include <QScrollArea>
#include <QWidget>
#include <QVBoxLayout>
#include <qpushbutton.h>
#include <QFrame>
#include "responsive_label.h"
#include<qlabel.h>
#include<QtCore>

ResponsiveWindow::ResponsiveWindow() {

    setWindowTitle("2811: Coursework 1");
    setMinimumSize(300, 300);

    createWidgets();
}

void ResponsiveWindow::createWidgets() {

	ResponsiveLayout * rl = new ResponsiveLayout();

	// add all the widgets we need to demonstrate all layouts
	rl->addWidget(new ResponsiveLabel(kNavTabs));
	rl->addWidget(new ResponsiveLabel(kBackButton));
	rl->addWidget(new ResponsiveLabel(kShoppingBasket));
	rl->addWidget(new ResponsiveLabel(kSignIn));
	rl->addWidget(new ResponsiveLabel(kHomeLink));
	rl->addWidget(new ResponsiveLabel(kSearchText));
	rl->addWidget(new ResponsiveLabel(kSearchOptions));
	rl->addWidget(new ResponsiveLabel(kSearchButton));
	rl->addWidget(new ResponsiveLabel(kAdvert));

	QGridLayout* l_grid = new QGridLayout();
	l_grid->addWidget(new ResponsiveLabel(kAdvert), 0, 0, 1, 4);	// add Advert
	int i = 1;
	for (i = 1; i < 10; i++) {	// add SearchResult and BuyButton
		ResponsiveLabel* label1 = new ResponsiveLabel(kSearchResult);
		ResponsiveLabel* label2 = new ResponsiveLabel(kBuy);
		l_grid->addWidget(label1, i, 0, 1, 3);
		l_grid->addWidget(label2, i, 3, 1, 1);
	}
	l_grid->addWidget(new ResponsiveLabel(kSearchBackward), i, 0, 1, 1);	//add SearchBackward button
	l_grid->addWidget(new ResponsiveLabel(kPage), i, 1, 1, 2);				//add PageNumber
	l_grid->addWidget(new ResponsiveLabel(kSearchForward), i++, 3, 1, 1);	//add SearchForward button
	l_grid->addWidget(new ResponsiveLabel(kFooter), i++, 0, 1, 4);			//add FatFooter

	ResponsiveLabel* rLabel = new ResponsiveLabel(kScroll);

	QScrollArea *area = new QScrollArea();
	QWidget* q = new QWidget(this);
	q->setLayout(l_grid);
	q->setGeometry(0, 0, 750, 750);
	area->setWidget(q);
	QGridLayout *l_grid2 = new QGridLayout();
	l_grid2->addWidget(area);
	rLabel->setLayout(l_grid2);
	rl->addWidget(rLabel);
	
	setLayout(rl);
}



// please DO NOT edit this file beyond this line
int main(int argc, char *argv[]) {

    // let's just check that Qt is operational first
    cout << "Qt version: " << QT_VERSION_STR << endl;

    // create the Qt Application
    QApplication app(argc, argv);

    // create a window. See respsonsive_window.cpp!
    if (argc-1)  {
        // grading-mode - run the screenshot subclass
        Screenshot screenshot;
        screenshot.show();
        // wait for the app to terminate
        return app.exec();
    } else {
        // interactive mode - run the regular superclass
        ResponsiveWindow window;
        window.show();
        // wait for the app to terminate
        return app.exec();
    }

}

